import os

rmtree_path = os.path.expanduser("~/Genealogy/ZebMoore_Ancestry.rmtree")
extension_path = os.path.expanduser("~/src/unifuzz/unifuzz.so")

UNIQUE_FACT_TYPES = {
    1: "Birth",
    2: "Death",
    4: "Burial",
    6: "Adoption",
    15: "Naturalization",
    16: "Emigration",
    17: "Immigration",

    3: "Christening",
    5: "Cremation",
    7: "Baptism",
    8: "Bar/Bat Mitzvah",
    9: "Blessing",
    10: "Census",
    11: "Circumcision",
    12: "Confirmation",
    13: "Divorce",
    14: "Education",
    15: "Naturalization",
    16: "Emigration",
    17: "Immigration",
    18: "Medical",
    19: "Military",
    20: "Mission",
    21: "Move",
    22: "Ordination",
    23: "Probate",
    24: "Property",
    25: "Religion",
    26: "Retirement",
    27: "Separation",
    28: "Will",
    29: "Residence",
    30: "Occupation",
    31: "Number of Children",
    32: "Cause of Death",
    33: "Funeral",
    34: "Travel",
    35: "Elective Office",
    36: "Elected",
    37: "Appointed",
    38: "Removed",
    39: "Excommunicated",
    40: "Trial",
    41: "Imprisonment",
    42: "Pension",
    43: "Resignation",
    44: "Legal",
    45: "Exile",
    46: "Deportation",
    47: "Miscellaneous"
}


# ----------------------------------
# U.S. State Reference Data
# ----------------------------------

# Map of state abbreviations to full names
STATE_ABBREVIATIONS = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
    "DC": "District of Columbia",
}

# Map of old-style abbreviations to full state names
# and some other state mappings and misspellings
OLD_STYLE_ABBR = {
    "Ala.": "Alabama",
    "Ariz.": "Arizona",
    "Ark.": "Arkansas",
    "Calif.": "California",
    "Colo.": "Colorado",
    "Conn.": "Connecticut",
    "Del.": "Delaware",
    "Fla.": "Florida",
    "Ga.": "Georgia",
    "Ill.": "Illinois",
    "Ind.": "Indiana",
    "Ia.": "Iowa",
    "Kan.": "Kansas",
    "Ky.": "Kentucky",
    "La.": "Louisiana",
    "Me.": "Maine",
    "Md.": "Maryland",
    "Mass.": "Massachusetts",
    "Mich.": "Michigan",
    "Minn.": "Minnesota",
    "Miss.": "Mississippi",
    "Mo.": "Missouri",
    "Mont.": "Montana",
    "Neb.": "Nebraska",
    "Nev.": "Nevada",
    "N.H.": "New Hampshire",
    "N.J.": "New Jersey",
    "N.M.": "New Mexico",
    "N.Y.": "New York",
    "N.C.": "North Carolina",
    "N.D.": "North Dakota",
    "Okla.": "Oklahoma",
    "Ore.": "Oregon",
    "Pa.": "Pennsylvania",
    "R.I.": "Rhode Island",
    "S.C.": "South Carolina",
    "S.D.": "South Dakota",
    "Tenn.": "Tennessee",
    "Tex.": "Texas",
    "Vt.": "Vermont",
    "Va.": "Virginia",
    "Wash.": "Washington",
    "W.Va.": "West Virginia",
    "Wis.": "Wisconsin",
    "Wyo.": "Wyoming",
    "Ill": "Illinois",
    "Ills": "Illinois",
    "ILL": "Illinois",
    "Illinoi": "Illinois",
    "Illinios": "Illinois",
    "Illiniois": "Illinois",
    "Wyo": "Wyoming",
    "Mass": "Massachusetts",
    "Missori": "Missouri",
    "N.m": "New Mexico",
    "1n": "Indiana",
    "Ind": "Indiana",
    "Kan": "Kansas",
    "Ore": "Oregon",
    "Ky": "Kentucky",
    "Fla": "Florida",
    "Kentucly": "Kentucky",
    "Jky": "Kentucky",
    "N.J": "New Jersey",
    "N.j": "New Jersey",
    "Mich": "Michigan",
    "Nebra": "Nebraska",
    "Tennessce": "Tennessee",
    "Tenn": "Tennessee",
    "Minn": "Minnesota",
    "Oiho": "Ohio",
    "West VA": "West Virginia",
    "Wash": "Washington",
    "D. C": "District of Columbia",
    "Colora": "Colorado",
    "Misssori": "Missouri",
}

STATE_NAMES = set(STATE_ABBREVIATIONS.values())

HISTORICAL_US_TERRITORIES = {
    "Indian Territory",
    "Oklahoma Territory",
    "Hawaii Territory",
    "Alaska Territory",
    "New Mexico Territory",
    "Arizona Territory",
    "Idaho Territory",
    "Dakota Territory",
    "Washington Territory",
    "Utah Territory",
    "Nebraska Territory",
    "Colorado Territory",
    "Montana Territory",
    "Wyoming Territory",
    "Nevada Territory",
    "Kansas Territory",
    "Northwest Territory",
    "Southwest Territory",
}


MEXICAN_STATES = [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila",
    "Colima",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "México",
    "Michoacán",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas",
    "Ciudad de México",
]

CANADIAN_PROVINCES = [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Nova Scotia",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Northwest Territories",
    "Nunavut",
    "Yukon",
]


# Corner cases:   "Georgia", "Mexico",
FOREIGN_COUNTRIES = {
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua & Deps",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Rep",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Columbia",
    "Comoros",
    "Congo",
    "Congo {Democratic Rep}",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "England",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Guam",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Ireland {Republic}",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea North",
    "Korea South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar, {Burma}",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Panamá",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Russian Federation",
    "Rwanda",
    "St Kitts & Nevis",
    "St Lucia",
    "Saint Vincent & the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome & Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Scotland",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad & Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Wales",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    "At sea",
}


COMMON_PLACE_MAPPINGS = {
    "Ambia": "Ambia, Benton, Indiana, USA",
    "Ballina": "Ballina, County Mayo, Ireland",
    "Baltimore": "Baltimore, Baltimore City, Maryland, USA",
    "Battle Creek": "Battle Creek, Calhoun, Michigan, USA",
    "Bavaria": "Bavaria, Germany",
    "Belfast": "Belfast, Ireland",
    "Blythedale": "Blythedale, Harrison, Missouri, USA",
    "Bohemia": "Bohemia, Czech Republic",
    "Boston": "Boston, Suffolk, Massachusetts, USA",
    "Bradenton": "Bradenton. Manatee, Florida, USA",
    "Camarillo": "Camarillo, Ventura, California, USA",
    "Campbellsburg": "Campbellsburg, Henry, Kentucky, USA",
    "Castleton": "Castleton, Marion, Indiana, USA",
    "Cherbourg": "Cherbourg, Manche, Basse-Normandie, France",
    "Chicago": "Chicago, Cook, Illinois, USA",
    "Davenport": "Davenport, Scott, Iowa, USA",
    "Detroit": "Detroit, Wayne, Michigan, USA",
    "Evanston": "Evanston, Cook, Illinois, USA",
    "Geneseo": "Geneseo, Henry, Illinois, USA",
    "Gest": "Gest, Henry, Kentucky, USA",
    "Gratz": "Gratz, Owen, Kentucky, USA",
    "Greencastle": "Greencastle, Putnam, Indiana, USA",
    "Harrodsburg": "Harrodsburg, Mercer, Kentucky, USA",
    "Indianapolis": "Indianapolis, Indiana, USA",
    "Kankakee": "Kankakee, Kankakee, Illinois, USA",
    "Kennewick": "Kennewick, Benton, Washington, USA",
    "Kosciusko": "Kosciusko County, Indiana, USA",
    "Lisle": "Lisle, DuPage, Illinois, USA",
    "Martinsville": "Martinsville, Morgan, Indiana, USA",
    "Missoula": "Missoula, Missoula, Montana, USA",
    "Moline": "Moline, Rock Island, Illinois, USA",
    "Munich": "Munich, Bavaria, Germany",
    "Noblesville": "Noblesville, Hamilton, Indiana, USA",
    "Ogden": "Ogden, Weber, Utah, USA",
    "Okemah": "Okemah, Okfuskee, Oklahoma, USA",
    "Oldham": "Oldham County, Kentucky, USA",
    "Olstein": "Olstein, Germany",
    "Olympia": "Olympia, Thurston, Washington, USA",
    "Orrville": "Orrville, Wayne, Ohio, USA",
    "Philadelphia": "Philadelphia, Philadelphia, Pennsylvania, USA",
    "Ranchester": "Ranchester, Sheridan, Wyoming, USA",
    "Rockbridge": "Rockbridge County, Virginia, USA",
    "Rockingham": "Rockingham County, Virginia, USA",
    "Russellville": "Russellville, Brown, Ohio, USA",
    "Sallisaw": "Sallisaw, Sequoyah, Oklahoma, USA",
    "Seattle": "Seattle, King, Washington, USA",
    "Shasta": "Shasta County, California, USA",
    "Spartanburg": "Spartanburg County, South Carolina, USA",
    "Succasunna": "Succasunna, Morris, New Jersey, USA",
    "Tacoma": "Tacoma, Pierce, Washington, USA",
    "Terre Haute": "Terre Haute, Indiana, USA",
    "Tippecanoe": "Tippecanoe County, Indiana, USA",
    "Topeka": "Topeka, Shawnee, Kansas, USA",
    "Trimble": "Trimble County, Kentucky, USA",
    "Vigo": "Vigo County, Indiana, USA",
    "Vinton": "Vinton, Vinton, Ohio, USA",
    "Welda": "Welda, Anderson, Kansas, USA",
    "Williamsfield": "Williamsfield, Knox, Illinois, USA",
    "Fort Knox": "Fort Knox, Hardin County, Kentucky, USA",
    "Rock Island": "Rock Island, Rock Island County, Illinois, USA",
    "San Francisco": "San Francisco, San Francisco County, California, USA",
    "Sioux City": "Sioux City, Woodbury County, Iowa, USA",
    "Los Angeles": "Los Angeles, Los Angeles County, California, USA",
    "Choctaw Nation": "Choctaw Nation, Indian Territory",
    "Arsenal Island": "Arsenal Island, Rock Island County, Illinois, USA",
    "County Leitrim": "County Leitrim, Ireland",
    "Floyds Knobs": "Floyds Knobs, Floyd County, Indiana, USA",
    "Iowa City": "Iowa City, Johnson County, Iowa, USA",
    "West Palm Beach": "West Palm Beach, Palm Beach County, Florida, USA",
    "Stillman Valley": "Stillman Valley, Ogle, Illinois, USA",
    "Santa Clara": "Santa Clara County, California, USA",
    "Poplar Bluff": "Poplar Bluff, Butler, Missouri, USA",
    "Ann Arbor": "Ann Arbor, Washtenaw, Michigan, USA",
    "Winter Haven": "Winter Haven, Polk, Florida, USA",
    "Salt Lake": "Salt Lake, Utah, USA",
    "Melrose Park": "Melrose Park, Cook, Illiniois, USA",
    "River Grove": "River Grove, Cook, Illiniois, USA",
    "New York City": "New York City, New York County, New York, USA",
    "Buffalo Grove": "Buffalo Grove, Lake, Illinois, USA",
    "Spokane City": "Spokane, Spokane County, Washington, USA",
}

ALT_COMMON_PLACE_MAPPINGS = {
    "Allegan": "Allegan, Allegan County, Michigan, USA",
    "Allen": "Allen County, Indiana, USA",
    "Allen County": "Allen County, Indiana, USA",
    "Anderson": "Anderson, Madison County, Indiana, USA",
    "Ark City": "Arkansas City, Cowley County, Kansas, USA",
    "Auburn": "Auburn, DeKalb County, Indiana, USA",
    "Ballard": "Ballard County, Kentucky, USA",
    "Berrien": "Berrien County, Michigan, USA",
    "Bethlehem": "Bethlehem, Northampton County, Pennsylvania, USA",
    "Brown County": "Brown County, Ohio, USA",
    "Calhoun": "Calhoun County, Michigan, USA",
    "Carroll": "Carroll County, Indiana, USA",
    "Clinton": "Clinton, Clinton County, Iowa, USA",
    "Clinton County": "Clinton County, Indiana, USA",
    "Columbus": "Columbus, Franklin County, Ohio, USA",
    "Decatur": "Decatur, Macon County, Illinois, USA",
    "Elkhart": "Elkhart, Elkhart County, Indiana, USA",
    "Eugene": "Eugene, Lane County, Oregon, USA",
    "Everett": "Everett, Snohomish County, Washington, USA",
    "Fairbury": "Fairbury, Livingston County, Illinois, USA",
    "Franklin": "Franklin, Johnson County, Indiana, USA",
    "Gaithersburg": "Gaithersburg, Montgomery County, Maryland, USA",
    "Grant City": "Grant City, Worth County, Missouri, USA",
    "Hamilton County": "Hamilton County, Indiana, USA",
    "Henry": "Henry County, Kentucky, USA",
    "Holland": "Holland, Ottawa County, Michigan, USA",
    "Jefferson": "Jefferson County, Kentucky, USA",
    "Johnson": "Johnson County, Indiana, USA",
    "Kansas City": "Kansas City, Jackson County, Missouri, USA",
    "LaGrange": "LaGrange, LaGrange County, Indiana, USA",
    "Lewistown": "Lewistown, Fulton County, Illinois, USA",
    "Lincoln": "Lincoln, Logan County, Illinois, USA",
    "Lockport": "Lockport, Will County, Illinois, USA",
    "Louisville": "Louisville, Jefferson County, Kentucky, USA",
    "Mitchell": "Mitchell, Lawrence County, Indiana, USA",
    "Norwalk": "Norwalk, Los Angeles County, California, USA",
    "Oakland": "Oakland, Alameda County, California, USA",
    "River Grove": "River Grove, Cook County, Illinois, USA",
    "San Bernardino": "San Bernardino, San Bernardino County, California, USA",
    "Springfield": "Springfield, Sangamon County, Illinois, USA",
    "St. George": "St. George, Washington County, Utah, USA",
    "St. Joseph": "St. Joseph, Buchanan County, Missouri, USA",
    "Stillman Valley": "Stillman Valley, Ogle County, Illinois, USA",
    "Texarkana": "Texarkana, Miller County, Arkansas, USA",
    "Warsaw": "Warsaw, Kosciusko County, Indiana, USA",
    "Wausau": "Wausau, Marathon County, Wisconsin, USA",
    "Westchester": "Westchester, Cook County, Illinois, USA",
    "Wilmington": "Wilmington, New Castle County, Delaware, USA",
    "Woodford": "Woodford County, Illinois, USA",
}







# Common street suffixes and directional tokens
STREET_SUFFIXES = [
    "Ave", "Avenue", "St", "Street", "Blvd", "Road", "Rd", "Drive", "Dr",
    "Ln", "Lane", "Terrace", "Way", "Place", "Pl", "Court", "Ct", "Loop",
    "Circle", "Crescent", "Parkway", "Pkwy", "Trail", "Trl", "Hwy", "Highway",
]
#    "South", "West", "North", "East", "SW", "N", "SE", "NE", "NW",

def load_us_counties(filename="us_counties.txt"):
    """Load county-state pairs from a pipe-delimited file into a list of tuples."""
    counties = []
    base_path = os.path.dirname(__file__)
    path = os.path.join(base_path, filename)

    with open(path, encoding="utf-8") as f:
        for line in f:
            parts = line.strip().split("|")
            if len(parts) == 2:
                counties.append((parts[0], parts[1]))
    return counties


# Make available globally in config
US_COUNTIES = load_us_counties()




